apiVersion: v1
kind: Pod
metadata:
  name: compliant-workload
  namespace: secure-ops
spec:
  serviceAccountName: secure-sa
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: busybox
    image: busybox:stable
    command: ["sleep", "3600"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
