apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: resiliency-lab
  name: payment-service
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m" 

        livenessProbe:
          httpGet:
            path: /
            port: 80
