apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: base64-lab
type: Opaque
data:
  password: YWRtaW4xMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-client
  namespace: base64-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-client
  template:
    metadata:
      labels:
        app: db-client
    spec:
      containers:
      - name: db-client
        image: busybox
        command: ["/bin/sh", "-c", "if [ "$DB_PASS" = "admin123" ]; then echo 'Connected!'; while true; do sleep 3600; done; else echo 'Authentication Failed'; exit 1; fi"]
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
